# Generated by Django 6.0.4 on 2026-04-17 11:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(max_length=20, unique=True, verbose_name="�����"),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="�������� ������"),
                ),
                (
                    "category",
                    models.CharField(
                        max_length=50, verbose_name="��������� (�����/������)"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="��������")),
            ],
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="���� � �����")),
                ("price_open", models.DecimalField(decimal_places=4, max_digits=14)),
                ("price_close", models.DecimalField(decimal_places=4, max_digits=14)),
                ("price_high", models.DecimalField(decimal_places=4, max_digits=14)),
                ("price_low", models.DecimalField(decimal_places=4, max_digits=14)),
                ("volume", models.BigIntegerField(verbose_name="����� ������")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="trading.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "������� ����",
                "verbose_name_plural": "������� ���",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "�������"), ("SELL", "�������")],
                        max_length=4,
                        verbose_name="��� ������",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="���� ������"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="����� ����������"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="trading.asset",
                        verbose_name="�����",
                    ),
                ),
            ],
        ),
    ]
