# Generated by Django 6.0.4 on 2026-04-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricehistory",
            name="price_close",
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price_high",
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price_low",
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name="pricehistory",
            name="price_open",
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
