# Generated by Django 6.0.4 on 2026-04-18 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0002_alter_pricehistory_price_close_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=80, verbose_name="���������")),
                ("phone", models.CharField(blank=True, max_length=32, verbose_name="�������")),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/", verbose_name="������"),
                ),
                ("bio", models.TextField(blank=True, verbose_name="������ ������")),
                (
                    "email_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=10,
                        verbose_name="��������� �����",
                    ),
                ),
                (
                    "phone_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="private",
                        max_length=10,
                        verbose_name="��������� ��������",
                    ),
                ),
                (
                    "full_name_visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        max_length=10,
                        verbose_name="��������� �����",
                    ),
                ),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="dark",
                        max_length=10,
                        verbose_name="���� ����������",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "������� ������������",
                "verbose_name_plural": "������� �������������",
            },
        ),
    ]
