# Generated by Django 6.0.4 on 2026-04-18 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "trading",
            "0006_alter_pricehistory_options_alter_userprofile_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={
                "ordering": ["-date"],
                "verbose_name": "История цены",
                "verbose_name_plural": "История цен",
            },
        ),
    ]
